print("Convert Uppercase Letter to Lowercase Letter\n\n")
k=input("Enter Uppercase Character ")
j=k.swapcase()
print("Uppercase Character you entered is ",k)
print("Converted Lowercase Character is ",j)
print("\n\nConvert Lowercase Character to Uppercase Character\n\n")
k=input("Enter Lowercase Character ")
j=k.swapcase()
print("Lowercase Character you entered is ",k)
print("Converted Uppercase Character is ",j)
