Student_name=input("Enter Student Name :")
Roll_no=input("Enter Roll No.:")
Branch=input("Enter Branch :")
year=input("Enter Academic year :")
print("Student Detail")
print("Student Name :",Student_name)
print("Roll Number :",Roll_no)
print("Branch :",Branch)
print("Academic Year :",year)